service:
  name: express-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 512
  stage: prod

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
